generateCalls = []
def generate(val):
    generateCalls.append(val)

l = {"generate": generate}
# This exec call would be taking its string from a .n file:
exec("a=3\nb=2\ngenerate(a*2)\npair,syntax = (a,b)",None,l)

print(f"We can inspect (say, for caching) local values: {l['a']}, here are all of them:")
print(l)
print("")
print(f"And we can inspect the exercise generated by our generate function:")
print(generateCalls)